image:
  file: .gitpod.dockerfile

prebuilds:
    master: true  # enable for the default branch
    branches: true  # enable for all branches in this repo
    pullRequests: false # disable for pull requests coming from this repo
    pullRequestsFromForks: false  # disable for pull requests coming from forks

tasks:
  - init: |
      premake5 --file=.gitpod.premake5.lua gmake
  - command: |
      bear make
      sh ./.gitpod.run.sh

vscode:
  extensions:
    - llvm-vs-code-extensions.vscode-clangd
    - vadimcn.vscode-lldb
    - ms-python.python
    - ms-toolsai.jupyter
    - eamodio.gitlens
    - ms-toolsai.jupyter-keymap
    - ms-toolsai.jupyter-renderers
    - Gruntfuggly.todo-tree
    - ms-vscode.hexeditor
