image:
  file: .gitpod.dockerfile

github:
  prebuilds:
      master: true
      branches: true
      pullRequests: false
      pullRequestsFromForks: false

tasks:
  - init: |
      premake5 --file=.gitpod.premake5.lua gmake
  - command: |
      bear make
      sh ./.gitpod.run.sh

vscode:
  extensions:
    - llvm-vs-code-extensions.vscode-clangd
    - vadimcn.vscode-lldb
    - ms-python.python
    - ms-toolsai.jupyter
    - eamodio.gitlens
    - ms-toolsai.jupyter-keymap
    - ms-toolsai.jupyter-renderers
    - Gruntfuggly.todo-tree
    - ms-vscode.hexeditor
