name: Build and Test

on: [push]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install Requirements
      run: |
        sudo apt-get install -y libclang-dev libffi-dev
        git clone https://github.com/wolkykim/qlibc.git
        cd qlibc
        ./configure --prefix=/usr/
        make
        sudo make install
        cd ..
        rm -fr qlibc/
    
    # - name: Initialize CodeQL
    #   uses: github/codeql-action/init@v2
    #   with:
    #       languages: cpp
    #       queries: security-and-quality

    - name: Build
      run: python setup.py build

    # - name: Perform CodeQL Analysis
    #   uses: github/codeql-action/analyze@v2

    - name: Install
      run: python setup.py install
    
    - name: Test
      run: bash ./.github/test.sh

    - name: Code Coverage
      run: |
        gcov -abcfu build/temp.linux-x86_64-3.9/src/CppTypeInfo.c
        gcov -abcfu build/temp.linux-x86_64-3.9/src/CppWrapper_PyTypes.c
        gcov -abcfu build/temp.linux-x86_64-3.9/src/PyC.c
        gcov -abcfu build/temp.linux-x86_64-3.9/src/TypeConversions.c

    - name: Upload Code Coverage
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./CppTypeInfo.c.gcov,./CppWrapper_PyTypes.c.gcov,./PyC.c.gcov,./TypeConversions.c.gcov
